MobileLoggingBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MobileLoggingBundle:Default:index }
    
MobileLoggingBundle_logger:
    resource: "@MobileLoggingBundle/Resources/config/routing/logger.yml"
    prefix:   /logger
