parameters:
#    mobile_logging.example.class: Mobile\LoggingBundle\Example

services:
#    mobile_logging.example:
#        class: %mobile_logging.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
